#!/usr/bin/python

import os
from time import sleep

print("Renamer for [sxee] format")
dir = raw_input("dir = ")
sep = raw_input("seperator (the x in [sxee]) = ")
season = raw_input("season (the s in [sxee]) = ")
#extension = raw_input("ext = ")

filenames = os.listdir(dir)

for filename in filenames:
    try:
        filenameProg = filename.replace(']','')
        filenameProg = filenameProg.replace('[','')
    except:
        print("No '[' or ']', continuing...")
    splitName = filenameProg.split(sep)
    newFileName = "S" + season + "E" + splitName[len(splitName) - 1]
    print(filename + "           " + dir + "/" + newFileName)
    os.rename(filename, dir + "/" + newFileName)
    sleep(0.5)
