#!/bin/bash

# The backup locations
etc_backup_dir="file:///mnt/nas_hdd1/Backup/Martijn/LinuxDesktop/etc"
home_backup_dir="file:///mnt/nas_hdd1/Backup/Martijn/LinuxDesktop/home"

# The dirs to be backed up
etc_dir="/etc"
home_dir="/home/martijn"

echo $(date)

# Actually doing the backing up
duplicity incr --no-encryption --volsize 4096 --full-if-older-than 2W $etc_dir $etc_backup_dir
duplicity incr --exclude /home/martijn/.cache/ --no-encryption --volsize 4096 --full-if-older-than 1M $home_dir $home_backup_dir
