#!/usr/bin/python

import os
import time
import sys

# Global variables
mp3_format = "libmp3lame -ab 128k"

def ConvertAudio(file, new_file, new_format):
#    print("avconv -i " + file + " -vcodec copy -acodec " + new_format + " " + new_file)
    os.popen("avconv -i " + file + " -vcodec copy -acodec " + new_format + " " + new_file)

def WholeDir(dir, sep, index, extension, new_format):
    files = os.listdir(dir)
    for filename in files:
        splitName = filename.split(sep)
        try:
            new_name = splitName[index] + extension
        except:
            sys.exit()
        ConvertAudio(dir + "/" + filename, dir + "/" + new_name, new_format)
        time.sleep(0.5)
    print("Done!")

dir = raw_input("dir = ")
sep = raw_input("seperator = ")
index = int(raw_input("index = "))
extension = raw_input("extension = ")

WholeDir(dir, sep, index, extension, mp3_format)
