#!/usr/bin/python

import sys
import ftplib

def GetFile(ftp, path, file, localpath):
    ftp.cwd(path)
    ftp.retrbinary("RETR " + file ,open(localpath, 'wb').write)

def Main():
    if sys.argv[1] == "-l":
        print("Logging in...")
        ftp = ftplib.FTP(sys.argv[2])
        ftp.login(sys.argv[3], sys.argv[4])
        GetFile(ftp, sys.argv[5], sys.argv[6], sys.argv[7])
    else:
        print("Downloading...")
        ftp = ftplib.FTP(sys.argv[1])
        ftp.login("ftp", "ftp")
        GetFile(ftp, sys.argv[2], sys.argv[3], sys.argv[4])

    ftp.quit()

try:
    if sys.argv[1] == "help":
        print("Usage: \n download_ftp_file $ip $path $file $localpath")
        print("or \n download_ftp_file -l $ip $username $password $path $file $localpath")
        sys.exit("Done!")
    else:
        Main()
except:
    sys.exit()
