#!/usr/bin/python

import os
import time
import sys

#dir = raw_input("dir =")
dir = sys.argv[1]

def main():
    files = os.listdir(dir)
    for file in files:
        newname = dir + "/downsampled/" + file
        os.popen("ffmpeg -i " + dir + "/" + file + " -s:0 1280x720 -acodec copy -scodec copy " + newname)
        time.sleep(0.5)
    print("Done!")

main()
