#!/usr/bin/python

import os
import time
import sys

dir = sys.argv[1]

extension = ".mp3"
try:
    extension = sys.argv[2]
except:
    pass

print("dir:\t" + dir)
print("extension:\t" + extension)

def main():
    files = os.listdir(dir)
    for file in files:
        newname = file + extension
        os.popen('ffmpeg -i "' + dir + '/' + file + '" -vn -acodec copy "' + newname + '" -loglevel quiet')
        time.sleep(0.5)
    print("Done!")

main()
