#!/usr/bin/python

import os
import time
import sys

#dir = raw_input("dir =")
dir = sys.argv[1]

def main():
    files = os.listdir(dir)
    for file in files:
        newname = file + ".mp3"
        os.popen('avconv -i "' + dir + '/' + file + '" "' + newname + '" -loglevel quiet')
        time.sleep(0.5)
    print("Done!")

main()
