#!/usr/bin/python

import os
import time
import sys

dir = "./"
extension = raw_input("extension = ")

files = os.listdir(dir)
for file in files:
    new_filename = file.replace(extension, "") + "-h264" + extension
    print new_filename
    
    command = "ffmpeg -i " + dir + "/" + file + " -c:a copy -x265-params crf=25 " + dir + "/" + new_filename
    print(command)
    print(os.popen(command).read())
