#!/usr/bin/python3
# A simple utility to generate a random password of a given length

from random import choice
import sys

#allowed_characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#$%+<=>?@_"
allowed_characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!$%?@_"

length = 24
try:
    if sys.argv[1] != None:
        length = int(sys.argv[1])
except:
    pass
print(''.join(choice(allowed_characters) for i in range(length)))
