#!/usr/bin/python

import os
import sys

# Color definitions for i3blocks
red = "#FF0000"
orange = "#FFCC00"
green = "#00CC00"

charge_crit = 15
charge_warn = 30

charging = False
data = ""

raw_data = os.popen("acpi -b").read().strip("Battery 0:").strip('\n')

if "Charging" in raw_data:
    charging = True
    data = raw_data.replace("Charging, ", '')
    print(data)
elif "Discharging" in raw_data:
    charging = False
    data = raw_data.replace("Discharging, ",'')
    print(data[:7] + "h remaining")

if len(sys.argv) > 1:
    if sys.argv[1] == "--i3blocks":
        print('')
        if charging:
            print(green)
        else:
            charge = int(data[:2])
            if charge > charge_warn:
                print(green)
            elif charge <= charge_warn and charge > charge_crit:
                print(orange)
            elif charge < charge_crit:
                print(red)
