#!/usr/bin/python

import os

# Get the battery percentage
rawData = os.popen("upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage").read()
data = rawData.replace('\n', '')
dataList = data.split(' ')

# Get the battery status
rawData = os.popen("upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state").read()
rawData = rawData.replace('\n', '')
dataList2 = rawData.split(' ')

charging_state_str = dataList2[len(dataList2) - 1]
charging_state = False

if charging_state_str == "discharging":
    charging_state = False
else:
    charging_state = True

if charging_state == False:
    print(dataList[len(dataList)-1] + "(bat)\n")
else:
    print(dataList[len(dataList)-1] + " (AC)\n")

level_int = int(dataList[len(dataList)-1].replace('%',''))

if level_int < 16 and charging_state == False:
    print("#FF000")
elif level_int > 39 and charging_state == False or charging_state == True:
    print("#00CC00")
elif level_int > 15 and level_int < 40 and charging_state == False:
    print("#FFCC00")
