#!/usr/bin/python

# Import
from os import popen
from RemoveAllChars import OnlyInts

temp_crit = 750
temp_warn = 550
temp_cold = 400

# Get the data
raw_data = popen("sensors | grep 'Physical id 0:'").read()
data = raw_data.replace('\n', '')
data = data.replace('+', '')
data_list = data.split(' ')

# Print final temp
print("CPU: " + data_list[4] + "\n")

# Remove all the non-int characters from dataList[4]
temp = int(OnlyInts(data_list[4]))

# Add colors for i3blocks
if temp >= temp_warn and temp < temp_crit:
    print("#FFCC00") # Orange
elif temp >= temp_crit:
    print("#FF000") # Red
elif temp <= temp_cold:
    print("#19D1FF") # Blue
else:
    print("#00CC00") # Green
