#!/usr/bin/python

from os import popen
import re

rpm_max = 1600
rpm_min = 600
rpm_crit = rpm_max - 100
rpm_warn = rpm_max - 400
rpm_ok = rpm_max / 2
rpm_low = rpm_min + 100

raw_data = popen("sensors | grep fan2").read()
p = re.compile('\d+')
results = p.findall(raw_data)
rpm = results[1]

print(rpm + " RPM (CPU fan)\n")

rpm = int(rpm)

# Add colors for i3blocks
if rpm <= rpm_ok and rpm > rpm_min and rpm > rpm_low:
    print("#00CC00") # Green
elif rpm >= rpm_warn and rpm < rpm_crit:
    print("#FFCC00") # Orange
elif rpm >= rpm_crit:
    print("#FF0000") # Red
elif rpm <= rpm_low:
    print("#19D1FF") # Blue
else:
    print("#00CC00") # Green
