#!/usr/bin/python

from os import popen
import sys
from RemoveAllChars import OnlyInts

temp_crit = 750
temp_warn = 550
temp_cold = 400

# Get the data
raw_data = popen("sensors | grep 'Physical id 0:'").read()
data = raw_data.replace('\n', '')
data = data.replace('+', '')
data_list = data.split(' ')

print("CPU: " + data_list[4])

# Remove all the non-int characters from dataList[4]
temp = int(OnlyInts(data_list[4]))

# Add colors for i3blocks if asked for
if len(sys.argv) > 1:
    if sys.argv[1] == "--i3blocks":
        if temp >= temp_warn and temp < temp_crit:
            print("\n#FFCC00") # Orange
        elif temp >= temp_crit:
            print("\n#FF000") # Red
        elif temp <= temp_cold:
            print("\n#19D1FF") # Blue
        else:
            print("\n#00CC00") # Green
