#!/usr/bin/python

import os
import re

raw_data = os.popen("ifconfig | grep -P '\d+\.\d+ [KMGT]?B'").read()
p = re.compile('\d+\.\d+ [KMGT]?B')
results = p.findall(raw_data)
total_down_eth0 = results[0]
total_down_wlan0 = results[4]

if total_down_wlan0 == '0.0 B':
    print("down: " + total_down_eth0)
elif total_down_eth0 == '0.0 B':
    print("down: " + total_down_wlan0)
else:
    print("down: " + total_down_eth0)
