#!/usr/bin/python

import os
import sys
import re

free_space_crit = 10
free_space_warn = 30

# Get the raw data and split everything
raw_data = os.popen("df -h /").read()
data_list = raw_data.split(' ')

# Use a regex to only have digit*,digit*G
p = re.compile('\d*,?\d+G')
results = p.findall(str(data_list))

# Print results
print(results[len(results) - 1] + " free")

# Use a regex to only have digits in the results
q = re.compile('\d+')
result_int = q.findall(results[len(results) - 1])

# Add colors for i3blocks
if len(sys.argv) > 1:
    if sys.argv[1] == "--i3blocks":
        if result_int > free_space_warn:
            print("\n#00CC00") # Green
        elif result_int <= free_space_warn and resultint > free_space_crit:
            print("\n#FFCC00") # Orange
        elif result_int <= free_space_crit:
            print("\n#FF0000") # Red
