#!/usr/bin/python

from os import popen
import sys
import re

rpm_crit = 85
rpm_warn = 75
rpm_ok = 30

raw_data = popen("nvidia-smi --query-gpu=fan.speed --format=csv,noheader").read()
data = raw_data.replace("\n", "")

p = re.compile('\d+')
results = p.findall(data)
data = int(results[0])

if data <= rpm_ok:
    print("off (GPUfans)")
elif data > rpm_ok and data < rpm_warn:
    print(str(data) + " (GPU fans)")
elif data >= rpm_warn and data < rpm_crit:
    print(str(data) + " (GPU fans)")
elif data >= rpm_crit:
    print(str(data) + " (GPU fans)")

if len(sys.argv) > 1:
    if sys.argv[1] == "--i3blocks":
        if data <= rpm_ok:
            print("\n#19D1FF") # Blue
        elif data > rpm_ok and data < rpm_warn:
            print("\n#00CC00") # Green
        elif data >= rpm_warn and data < rpm_crit:
            print("\n#FFCC00") # Orange
        elif data >= rpm_crit:
            print("\n#FF0000") # Red
