#!/usr/bin/python

import os
import re
import socket

serverip = "192.168.1.1"

def is_connected_wan():
    try:
        raw_data = os.popen("ping -c 1 " + serverip + " | grep -P '\d received'").read()
        p = re.compile('\d received')
        result = p.findall(raw_data)

        if result[len(result) - 1] == '1 received':
            return True
        else:
            return False
    except:
        return False

if is_connected_wan() == True:
    print("LAN: up\n")
    print("#00CC00")
else:
    print("LAN: down\n")
    print("#FF0000")
