#!/usr/bin/python

import os
import re

raw_data = os.popen("ifconfig | grep -P '\d+\.\d+ [KMGT]?B'").read()
p = re.compile('\d+\.\d+ [KMGT]?B')
results = p.findall(raw_data)
total_up_eth0 = results[1]
total_up_wlan0 = results[len(results) - 1]

if total_up_eth0 == '0.0 B':
    print("up: " + total_up_wlan0)
elif total_up_wlan0 == '0.0 B':
    print("up: " + total_up_eth0)
else:
    print("up: " + total_up_eth0)
