#!/usr/bin/python

# Import
import os
import re

total_ram = 8.0 # In GB
ram_usage_crit = total_ram - 0.5
ram_usage_warn = total_ram - 2

raw_data = os.popen("free -h").read()
data_list = raw_data.split(' ')
p = re.compile('\d*,?\d+[BKMG]')
results = p.findall(str(data_list))
#print str(results)

print(results[len(results) - 5] + " RAM used\n")

q = re.compile('\d+,?\d+')
digits_only = q.match(results[len(results) - 5]).group()
result_float = float(digits_only.replace(',','.'))

# Add colors for i3blocks
if result_float >= ram_usage_crit and result_float < total_ram:
    print("#FF0000") # Red
elif result_float >= ram_usage_warn and result_float < ram_usage_crit:
    print("#FFCC00") # Orange
else:
    print("#00CC00") # Green
