#!/usr/bin/python

import time
import os

def GetCPUTemp():
    rawData = os.popen("sensors | grep 'Physical id 0:'").read()
    data = rawData.replace('\n', '')
    data = data.replace('+', '')
    dataList = data.split(' ')
    return "T_CPU: " + dataList[4]

def GetUp():
    rawData = os.popen("ifconfig | grep 'RX bytes' -m 1").read()
    dataList = rawData.split('(')
    dataUp = dataList[2].split(')')[0]
    return "up: " + dataUp

def GetDown():
    rawData = os.popen("ifconfig | grep 'RX bytes' -m 1").read()
    dataList = rawData.split('(')
    dataDown = dataList[1].split(')')[0]
    return "down: " + dataDown

def GetMotherboardTemp():
    rawData = os.popen("sensors | grep 'SYSTIN:'").read()
    data = rawData.replace('+', '')
    data = data.replace('\n', '')
    dataList = data.split(' ')
    return "T_Motherboard: " + dataList[9]

print os.popen("date").read().replace('\n', '') + " , " + GetCPUTemp() + " , " +GetMotherboardTemp()
