#!/usr/bin/python

import eyeD3
import os
from time import sleep

print("mp3_tag_add_from_filename, Create artist/title tag based on filename. Filename format: Artist - Song name")
dir = raw_input("dir = ")

file_list = os.listdir(dir)

for file in file_list:
    #print file
    if file[len(file) - 1] == "3":
        if eyeD3.isMp3File(dir + file):
            # File is a mp3 file
            tag = eyeD3.Tag()
            tag.link(dir + file)
            # If the length is zero, there's no artist information
            if len(tag.getArtist()) == 0:
                # Check if the title also misses
                if len(tag.getTitle()) == 0:
                    # Continue with creating tags based on the filename
                    filename = file.replace(".mp3","")
                    filename_split = filename.split("-")
                    try:
                        artist = filename_split[0].strip()
                        title = filename_split[1].strip()
                        print artist
                        print title
                        tag.setArtist(artist)
                        tag.setTitle(title)
                        tag.setGenre(179)
                        tag.update(eyeD3.ID3_V1_1)
                        print("Succesfully updated ID3 tags")
                    except IndexError:
                        print("Title index out of range")
                else:
                    # Tag exists, therefore don't edit it
                    pass
            else:
                # Tag exists, continue with next file
                pass 
        else:
            print("File is not a mp3 file.")
    else:
        print("File extension does not end with a 3 indicating a mp3 file.")
