#!/bin/bash

size=$1
echo "$size"
if [ -z $size ]; then
    size="1024M"
fi
echo "$size"
sudo mount -t tmpfs -o size=$size tmpfs /mnt/ramdisk

sudo mkdir /mnt/ramdisk/martijn
sudo chown martijn:martijn /mnt/ramdisk/martijn
setfacl -R -d -m o::--- /mnt/ramdisk/martijn
