#!/bin/bash

size=$1
if [ -z $size ]; then
    echo "No custom size specified..."
    size="1024M"
fi
echo "Using size: $size"
sudo mount -t tmpfs -o size=$size tmpfs /mnt/ramdisk

sudo mkdir /mnt/ramdisk/martijn
sudo chown martijn:martijn /mnt/ramdisk/martijn
setfacl -R -d -m o::--- /mnt/ramdisk/martijn
