#!/usr/bin/python

import os
import time

def main():
    dataList = []

    dataList.append(os.popen("uptime").read() + "\n")
    dataList.append(os.popen("cpuload").read())
    dataList.append("CPU temp: \n" + os.popen("getcputemp").read())
    dataList.append("Network stats:\n" + os.popen("getdown").read())
    dataList.append(os.popen("getup").read() + "\n")
    dataList.append("Memory stats:\n" + os.popen("free -h").read() + "\n")
    dataList.append("Drive stats:  TOTAL | USED | FREE\n" + os.popen("df -h | grep '/dev/' && df -h --total | grep 'total'").read())

    data = str(dataList)
    data = data.replace('[', '')
    data = data.replace(']', '')
    data = data.replace(',', '')

    #os.popen("echo " + data + " > /var/www/html/status")
    #for data in dataList:
    #    print data

    file = open("/var/www/html/status.txt", "w")

    for data in dataList:
        file.write(data)

while True:
    main()
    time.sleep(30)
