#!/usr/bin/python

import os

time = os.popen("date '+%Y-%m-%d %H:%M'").read()
raw_data = os.popen("date +%H%M%S").read()
raw_data = raw_data.replace("\n","")
color = "#" + raw_data

print time
print color
