#!/usr/bin/python

import os

time = os.popen("date '+%H:%M %d-%m-%Y'").read()
raw_data = os.popen("date +%H%M%S").read()
raw_data = raw_data.replace("\n","")
color = "#" + raw_data

print time
print color
