#!/usr/bin/python3
# Small script to validate a given IP address

import socket
import sys

try:
    socket.inet_pton(socket.AF_INET, sys.argv[1])
    print(sys.argv[1] + " is a valid IPv4 address")
except socket.error:
    try:
        socket.inet_pton(socket.AF_INET6, sys.argv[1])
        print(sys.argv[1] + " is a valid IPv6 address")
    except socket.error:
        print("Invalid IP address")
except IndexError:
    print("No IP given")
