#!/bin/bash

vboxmanage startvm "VirtualRouter" --type headless

echo "Waiting for VirtualRouter to boot..."
sleep 60

vboxmanage startvm "VirtualServer-Main" --type headless
vboxmanage startvm "VirtualServer-FTP" --type headless
vboxmanage startvm "VirtualServer-Samba" --type headless
